import "./globals.css";
import { AuthProvider } from "@/context/auth-context";
import { GlobalContextProvider } from "@/context/context";
import { Toaster } from "sonner";
import NextTopLoader from "nextjs-toploader";

export const metadata = {
  title: "PennyWise",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <AuthProvider>
          <NextTopLoader
            color="#4845D2"
            showSpinner={false}
            shadow={false}
            height={5}
          />
          <GlobalContextProvider>
            {children}
            <Toaster
              toastOptions={{
                classNames: {
                  error: "bg-red-400 text-white",
                  success: "bg-green-500 text-white",
                  warning: "text-yellow-400",
                  info: "bg-blue-400",
                },
              }}
            />
          </GlobalContextProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
